import 'dart:io';
import 'package:csv/csv.dart';
import 'package:flutter/foundation.dart';
import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import '../models/transaction_model.dart';

/// Export transactions as CSV or shareable file.
class ExportService {
  ExportService._();
  static final ExportService instance = ExportService._();

  /// Export transactions as CSV and share.
  Future<void> exportCsv(List<Txn> transactions, {String? title}) async {
    final headers = ['Date', 'Title', 'Category', 'Type', 'Amount'];
    final rows = transactions.map((t) => [
      DateFormat('yyyy-MM-dd').format(t.date),
      t.title,
      t.category,
      t.type,
      t.amount.toStringAsFixed(2),
    ]).toList();

    final csv = const ListToCsvConverter().convert([headers, ...rows]);
    final file = await _writeToFile(csv, title ?? 'transactions', 'csv');
    await _share(file, 'Expense Report (CSV)');
  }

  /// Export a text-based report and share.
  Future<void> exportReport(List<Txn> transactions, {required int month, required int year, required double income, required double expense}) async {
    final monthName = DateFormat('MMMM yyyy').format(DateTime(year, month));
    final buf = StringBuffer();
    buf.writeln('═══════════════════════════════════════');
    buf.writeln('   EXPENSE TRACKER — MONTHLY REPORT');
    buf.writeln('   $monthName');
    buf.writeln('═══════════════════════════════════════');
    buf.writeln();
    buf.writeln('Income:   ₹${income.toStringAsFixed(2)}');
    buf.writeln('Expense:  ₹${expense.toStringAsFixed(2)}');
    buf.writeln('Balance:  ₹${(income - expense).toStringAsFixed(2)}');
    buf.writeln();
    buf.writeln('───────────────────────────────────────');
    buf.writeln('TRANSACTIONS (${transactions.length})');
    buf.writeln('───────────────────────────────────────');
    for (final t in transactions) {
      final sign = t.isIncome ? '+' : '-';
      buf.writeln('${DateFormat('dd MMM').format(t.date)}  $sign₹${t.amount.toStringAsFixed(2)}  ${t.title}  [${t.category}]');
    }
    buf.writeln();
    buf.writeln('Generated by Expense Tracker');

    final file = await _writeToFile(buf.toString(), 'report_$monthName', 'txt');
    await _share(file, 'Expense Report — $monthName');
  }

  Future<File> _writeToFile(String content, String name, String ext) async {
    final dir = await getApplicationDocumentsDirectory();
    final file = File('${dir.path}/${name.replaceAll(' ', '_')}.$ext');
    return file.writeAsString(content);
  }

  Future<void> _share(File file, String subject) async {
    try {
      await Share.shareXFiles([XFile(file.path)], subject: subject);
    } catch (e) {
      debugPrint('Share error: $e');
    }
  }
}
